services:
  fastapi:
    image: fastapi
    build:
      context: fastapi
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi/app:/app
      - /fastapi/app/__pycache__/

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./vue-client
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
    volumes:
      - ./vue-client:/app
      - ./vue-client/node_modules:/app/node_modules
  # telegram-bot:
  #   build: .
  #   container_name: telegram-bot-container
  #   environment:
  #     TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN} # Use environment variable from .env file
  #   volumes:
  #     - ./telegram-bot:/telegram-bot # Mount current directory to /app in the container
  #   restart: unless-stopped
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
