FROM python:3.12

WORKDIR /app

COPY requirements.txt /app/

RUN apt-get update && apt-get install -y \
  build-essential \
  gcc \
  libffi-dev \
  libssl-dev \
  && apt-get clean

RUN pip install --no-cache-dir -r requirements.txt


COPY app /app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--debug"]