FROM node:20-alpine AS builder

ENV NODE_ENV=development
ENV NUXT_PORT=3000

RUN apk add --no-cache bash curl && \
  corepack enable && \
  corepack prepare pnpm@latest --activate

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000

CMD ["pnpm", "dev"]
